import { Config } from "./audio/Config"

export const CONFIG: Config = {
    noteSubdivision: "8n",
    sequenceSteps: 16,
    trackData: [
        {
            id: "kick",
            name: "Kick",
            sample: "assets/kick.wav",
            sequenceNotes: [
                true,
                false,
                false,
                false,
                true,
                false,
                false,
                false,
                true,
                false,
                false,
                false,
                true,
                false,
                false,
                false,
            ],
        },
        {
            id: "snare",
            name: "Snare",
            sample: "assets/snare.wav",
            sequenceNotes: [
                false,
                false,
                true,
                false,
                false,
                false,
                true,
                false,
                false,
                false,
                true,
                false,
                false,
                false,
                true,
                true,
            ],
        },
        {
            id: "hh",
            name: "HiHat",
            sample: "assets/hihat.wav",
            sequenceNotes: [
                true,
                true,
                true,
                true,
                true,
                true,
                true,
                true,
                true,
                true,
                true,
                true,
                true,
                false,
                false,
                false,
            ],
        },
        {
            id: "stick1",
            name: "Stick",
            sample: "assets/stick1.wav",
            sequenceNotes: [
                false,
                false,
                true,
                false,
                false,
                false,
                true,
                false,
                false,
                false,
                true,
                false,
                true,
                true,
                true,
                true,
            ],
        },
        {
            id: "perc1",
            name: "Perc.",
            sample: "assets/perc1.wav",
            sequenceNotes: [
                false,
                false,
                false,
                true,
                false,
                false,
                false,
                false,
                false,
                false,
                true,
                true,
                false,
                false,
                false,
                false,
            ],
        },
        {
            id: "clap",
            name: "Clap",
            sample: "assets/clap.wav",
            sequenceNotes: [
                false,
                false,
                true,
                false,
                false,
                false,
                true,
                false,
                false,
                false,
                true,
                false,
                false,
                false,
                false,
                false,
            ],
        },
        {
            id: "snap",
            name: "Snap",
            sample: "assets/snap.wav",
            sequenceNotes: [
                false,
                false,
                false,
                true,
                true,
                false,
                true,
                false,
                true,
                false,
                false,
                true,
                true,
                false,
                false,
                false,
            ],
        },
        {
            id: "shaker",
            name: "Shaker",
            sample: "assets/shaker.wav",
            sequenceNotes: [
                true,
                true,
                true,
                true,
                true,
                true,
                true,
                true,
                true,
                true,
                true,
                true,
                true,
                true,
                true,
                true,
            ],
        },
    ],
}
